### ISSUE TITLE
Tune the current LoRA-affinity algorithm to reduce flapping

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/llm-instance-gateway#75]
/assign @kaushikmitr

**Comment by kaushikmitr** [comment]
@ahg-g This issue is addressed in this PR: https://github.com/kubernetes-sigs/llm-instance-gateway/pull/78
based on controller changes also needed to make some manifest updates: https://github.com/kubernetes-sigs/llm-instance-gateway/pull/81
